export const LOGIN_USER='LOGIN_USER', REGISTER_USER='REGISTER_USER',LOGOUT_USER='LOGOUT_USER',AUTH_USER='AUTH_USER';
export const FETCH_ITEM='FETCH_ITEM', ADD_ITEM='ADD_ITEM',DEL_ITEM='DEL_ITEM',MOD_ITEM='MOD_ITEM',ADD_CART='ADD_CART',DEL_CART='DEL_CART';
